// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Pico2UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_Label1;


// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_TabView2;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Switch4;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Switch5;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_TabPage3;

lv_obj_t * ui_Image7;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Switch6;

lv_obj_t * ui_Image8;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Switch7;

lv_obj_t * ui_Image9;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Switch8;

lv_obj_t * ui_Image10;
lv_obj_t * ui_btn1;
lv_obj_t * ui_btn2;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;

lv_obj_t * ui_Label12;

// string Course_Name;

lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_01_home_[1] = {&ui_img_01_home_03_png};
const lv_img_dsc_t * ui_imgset_nav_[2] = {&ui_img_nav_01_png, &ui_img_nav_02_png};
const lv_img_dsc_t * ui_imgset_options_[2] = {&ui_img_options_01_png, &ui_img_options_02_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
