// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Pico2UI

#ifndef _PICO2UI_UI_H
#define _PICO2UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// extern string Course_Name;
extern int Style_1;
extern int Style_2;
extern int Style_3;
extern int Style_4;
extern int game_1;
extern int game_2;
extern int game_3;
extern int Curriculum_flag;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Switch4;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Switch5;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui____initial_actions0;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Switch6;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Switch7;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Switch8;

extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_btn1;
extern lv_obj_t * ui_btn2;

extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;

extern lv_obj_t * ui_Label12;


LV_IMG_DECLARE(ui_img_01_home_03_png);    // assets/01_Home_03.png
LV_IMG_DECLARE(ui_img_nav_02_png);    // assets/nav_02.png
LV_IMG_DECLARE(ui_img_nav_01_png);    // assets/nav_01.png
LV_IMG_DECLARE(ui_img_options_02_png);    // assets/Options_02.png
LV_IMG_DECLARE(ui_img_options_01_png);    // assets/Options_01.png
LV_IMG_DECLARE(ui_img_1662428085);    // assets/Options_01-1.png

LV_IMG_DECLARE(ui_img_1662400658);    // assets/Options_02-1.png

LV_IMG_DECLARE(ui_img_crowpi_320x2400_game_02_01_png);
LV_IMG_DECLARE(ui_img_crowpi_320x2400_game_02_02_png);
LV_IMG_DECLARE(ui_img_bg_11_png);    // assets/bg_11.png
LV_IMG_DECLARE(ui_img_icon_01_png);    // assets/icon_01.png
LV_IMG_DECLARE(ui_img_icon_03_png);    // assets/icon_03.png
LV_IMG_DECLARE(ui_img_icon_02_png);    // assets/icon_02.png

LV_IMG_DECLARE(ui_img_pico_nav_01_png);    // assets/bg_11.png
LV_IMG_DECLARE(ui_img_pico_icon_01_png);    // assets/icon_01.png
LV_IMG_DECLARE(ui_img_pico_icon_02_png);    // assets/icon_03.png
LV_IMG_DECLARE(ui_img_pico_icon_03_png);    // assets/icon_02.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
