// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Pico2UI

#include "ui.h"
int Style_1 = 0;
int Style_2 = 0;
int Style_3 = 0;
int Style_4 = 0;

int game_1 = 0;
int game_2 = 0;
int game_3 = 0;

int Curriculum_flag = 0;

static void Style_1_cd(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (lv_obj_has_state(ui_Switch1, LV_STATE_CHECKED))
    {
        Style_1 = 1;
        lv_obj_clear_state(ui_Switch3, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Switch4, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Switch5, LV_STATE_CHECKED);
        Style_2 = 0;
        Style_3 = 0;
        Style_4 = 0;
    }
    else
    {
        Style_1 = 0;
    }
}
static void Style_2_cd(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (lv_obj_has_state(ui_Switch3, LV_STATE_CHECKED))
    {
        Style_2 = 1;
        lv_obj_clear_state(ui_Switch1, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Switch4, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Switch5, LV_STATE_CHECKED);
        Style_1 = 0;
        Style_3 = 0;
        Style_4 = 0;
    }
    else
    {
        Style_2 = 0;
    }
}
static void Style_3_cd(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (lv_obj_has_state(ui_Switch4, LV_STATE_CHECKED))
    {
        lv_obj_clear_state(ui_Switch1, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Switch3, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Switch5, LV_STATE_CHECKED);
        Style_2 = 0;
        Style_1 = 0;
        Style_4 = 0;
        Style_3 = 1;
    }
    else
    {
        Style_3 = 0;
    }
}
static void Style_4_cd(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (lv_obj_has_state(ui_Switch5, LV_STATE_CHECKED))
    {
        lv_obj_clear_state(ui_Switch1, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Switch3, LV_STATE_CHECKED);
        lv_obj_clear_state(ui_Switch4, LV_STATE_CHECKED);
        Style_4 = 1;
        Style_2 = 0;
        Style_3 = 0;
        Style_1 = 0;
    }
    else
    {
        Style_4 = 0;
    }
}
static void game1_cd(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (code == LV_EVENT_CLICKED)
    {

        game_1 = 1;
    }
}
static void game2_cd(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (code == LV_EVENT_CLICKED)
    {

        game_2 = 1;
    }
}
static void game3_cd(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (code == LV_EVENT_CLICKED)
    {

        game_3 = 1;
    }
}

static void Curriculum_cd(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (code == LV_EVENT_CLICKED)
    {
        if (Curriculum_flag == 0)
        {

            lv_label_set_text(ui_Label11, "ON");
            Curriculum_flag = 1;
        }
        else
        {

            lv_label_set_text(ui_Label11, "OFF");
            Curriculum_flag = 0;
        }
    }
}
void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView2 = lv_tabview_create(ui_Screen2, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView2, lv_pct(100));
    lv_obj_set_height(ui_TabView2, lv_pct(100));

    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TabView2, LV_STATE_CHECKED | LV_STATE_FOCUSED); /// States
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE);             /// Flags
    lv_obj_set_style_bg_color(ui_TabView2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_TabView2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(ui_TabView2, lv_color_hex(0x09CF1E), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_TabView2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x27A33E),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView2), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0xF9F9F9),
                                LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView2), 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x11E03E),
                              LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView2), 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_src(lv_tabview_get_tab_btns(ui_TabView2), &ui_img_nav_02_png, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x349520),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView2), 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(lv_tabview_get_tab_btns(ui_TabView2), &ui_img_nav_02_png,
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0xFFFFFF),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView2), 255, LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(lv_tabview_get_tab_btns(ui_TabView2), &ui_img_nav_01_png,
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0xFCFCFC),
                                LV_PART_ITEMS | LV_STATE_FOCUSED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView2), 255, LV_PART_ITEMS | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(lv_tabview_get_tab_btns(ui_TabView2), &ui_img_nav_01_png,
                                LV_PART_ITEMS | LV_STATE_FOCUSED);
    lv_obj_set_style_bg_img_src(lv_tabview_get_tab_btns(ui_TabView2), &ui_img_nav_01_png, LV_PART_ITEMS | LV_STATE_USER_1);

    ui_TabPage1 = lv_tabview_add_tab(ui_TabView2, "Atmosphere\n      Lights");
    lv_obj_set_style_bg_color(ui_TabPage1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TabPage1, lv_color_hex(0x03DE1E), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_TabPage1, lv_color_hex(0x00AC4F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_TabPage1, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_TabPage1);
    lv_img_set_src(ui_Image3, &ui_img_1662400658);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image3, -5);
    lv_obj_set_y(ui_Image3, -65);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label2 = lv_label_create(ui_Image3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label2, -107);
    lv_obj_set_y(ui_Label2, -1);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Style 1");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Image3);
    lv_obj_set_width(ui_Switch1, 60);
    lv_obj_set_height(ui_Switch1, 35);
    lv_obj_set_x(ui_Switch1, 101);
    lv_obj_set_y(ui_Switch1, -1);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x0B6218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x24BE42), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Switch1, Style_1_cd, LV_EVENT_VALUE_CHANGED, NULL);

    ui_Image4 = lv_img_create(ui_TabPage1);
    lv_img_set_src(ui_Image4, &ui_img_1662400658);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image4, -5);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label4 = lv_label_create(ui_Image4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label4, -107);
    lv_obj_set_y(ui_Label4, -1);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Style 2");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Image4);
    lv_obj_set_width(ui_Switch3, 60);
    lv_obj_set_height(ui_Switch3, 35);
    lv_obj_set_x(ui_Switch3, 101);
    lv_obj_set_y(ui_Switch3, -1);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x0B6218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x24BE42), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Switch3, Style_2_cd, LV_EVENT_VALUE_CHANGED, NULL);

    ui_Image5 = lv_img_create(ui_TabPage1);
    lv_img_set_src(ui_Image5, &ui_img_1662400658);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image5, -5);
    lv_obj_set_y(ui_Image5, 65);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label5 = lv_label_create(ui_Image5);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label5, -107);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Style 3");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Image5);
    lv_obj_set_width(ui_Switch4, 60);
    lv_obj_set_height(ui_Switch4, 35);
    lv_obj_set_x(ui_Switch4, 101);
    lv_obj_set_y(ui_Switch4, -1);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x0B6218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x24BE42), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Switch4, Style_3_cd, LV_EVENT_VALUE_CHANGED, NULL);

    ui_Image6 = lv_img_create(ui_TabPage1);
    lv_img_set_src(ui_Image6, &ui_img_1662400658);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Image6, -5);
    lv_obj_set_y(ui_Image6, 130);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label6 = lv_label_create(ui_Image6);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label6, -107);
    lv_obj_set_y(ui_Label6, -1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Style 4");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch5 = lv_switch_create(ui_Image6);

    // lv_obj_set_style_pad_left(ui_Switch5, 20, LV_PART_ANY);
    // lv_obj_set_style_pad_right(ui_Switch5, 20, LV_PART_ANY);
    // lv_obj_set_style_pad_top(ui_Switch5, 20, LV_PART_ANY);
    // lv_obj_set_style_pad_bottom(ui_Switch5, 20, LV_PART_ANY);

    lv_obj_set_width(ui_Switch5, 60);
    lv_obj_set_height(ui_Switch5, 35);
    lv_obj_set_x(ui_Switch5, 101);
    lv_obj_set_y(ui_Switch5, -1);
    lv_obj_set_align(ui_Switch5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0x0B6218), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch5, lv_color_hex(0x24BE42), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Switch5, Style_4_cd, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_set_ext_click_area(ui_Switch5, 10);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView2, "  Course\nLearning");

    lv_obj_set_style_bg_color(ui_TabPage2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TabPage2, lv_color_hex(0x03DE1E), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_TabPage2, lv_color_hex(0x00AC4F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_TabPage2, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image11 = lv_btn_create(ui_TabPage2);
    lv_obj_set_width(ui_Image11, 284);
    lv_obj_set_height(ui_Image11, 48);
    lv_obj_set_x(ui_Image11, -5);
    lv_obj_set_y(ui_Image11, 0);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Image11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Image11, &ui_img_1662400658, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Image11);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    // Set the course title
/*The course title needs to be modified before compiling the course.*/
/*The following are the titles of each course:
L1_LED_control
L2_Button_Control_LED
L3_Breathing_LED
L4_2.4_inch_TFT_display
L5_Traffic_light
L6_Intelligent_street
L7_Ultrasonic_ranging
L8_Obstacle_close_range
L9_Brightness_display
L10_Temperature_Humidity
L11_Servo_control
L12_IR_control_LED
L13_Weather_reminder
L14_Servo_angle_control
L15_Polite_automatic_door
L16_Sound_Reminder
L17_Calculation_of_acceleration
L18_Smart_corridor_light
L19_simple_calculator
L20_Hall_counter
L21_smoke_alarm

After selecting a course, replace it with the second parameter of the lv_label_set_text() function.
The following uses Lesson 17 as an example.

If the course title is not fully displayed, modify the second parameter of the lv_obj_set_x() function. This parameter means taking 0 as the center point.
The smaller the number, the more to the left the title will be. Conversely, the larger the number, the more to the right it will be.
*/
    lv_obj_set_x(ui_Label10, -40);
    lv_obj_set_y(ui_Label10, 0);
    lv_label_set_text(ui_Label10, "L17_Calculation_of_acceleration");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Image11);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label11, 100);
    lv_obj_set_y(ui_Label11, -1);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "OFF");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image11, Curriculum_cd, LV_EVENT_ALL, NULL);

    // Open when burning the factory program
    //     ui_Label10 = lv_label_create(ui_TabPage2);
    //     lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);  /// 1
    //     lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT); /// 1
    //     lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);

    // lv_obj_set_x(ui_Label10,0);
    // lv_obj_set_y(ui_Label10, 0);
    // lv_label_set_text(ui_Label10, "If you need to use the course, \nplease flash the course firmware!");
    //     lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    //     lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView2, "MiniGame");

    lv_obj_set_style_bg_color(ui_TabPage3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_TabPage3, lv_color_hex(0x03DE1E), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabPage3, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_TabPage3, lv_color_hex(0x00AC4F), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_TabPage3, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image7 = lv_btn_create(ui_TabPage3);
    lv_obj_set_width(ui_Image7, 284);
    lv_obj_set_height(ui_Image7, 48);
    lv_obj_set_x(ui_Image7, -5);
    lv_obj_set_y(ui_Image7, -65);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Image7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Image7, &ui_img_1662400658, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Image7);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label7, -77);
    lv_obj_set_y(ui_Label7, -1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Little Dinosaur");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Switch6 = lv_switch_create(ui_Image7);
    // lv_obj_set_width(ui_Switch6, 60);
    // lv_obj_set_height(ui_Switch6, 35);
    // lv_obj_set_x(ui_Switch6, 101);
    // lv_obj_set_y(ui_Switch6, -1);
    // lv_obj_set_align(ui_Switch6, LV_ALIGN_CENTER);
    // lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0x0B6218), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_bg_color(ui_Switch6, lv_color_hex(0x24BE42), LV_PART_KNOB | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Switch6, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Image7, game1_cd, LV_EVENT_ALL, NULL);

    ui_Image8 = lv_btn_create(ui_TabPage3);
    lv_obj_set_width(ui_Image8, 284);
    lv_obj_set_height(ui_Image8, 48);
    lv_obj_set_x(ui_Image8, -5);
    lv_obj_set_y(ui_Image8, 0);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Image8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Image8, &ui_img_1662400658, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_img_set_src(ui_Image8, &ui_img_1662400658);
    // lv_obj_set_width(ui_Image8, 284);  /// 1
    // lv_obj_set_height(ui_Image8, 48); /// 1
    // lv_obj_set_x(ui_Image8, -5);
    // lv_obj_set_y(ui_Image8, 0);
    // lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    // lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Label8 = lv_label_create(ui_Image8);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label8, -77);
    lv_obj_set_y(ui_Label8, -1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Bouncing ball");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Switch7 = lv_switch_create(ui_Image8);
    // lv_obj_set_width(ui_Switch7, 60);
    // lv_obj_set_height(ui_Switch7, 35);
    // lv_obj_set_x(ui_Switch7, 101);
    // lv_obj_set_y(ui_Switch7, -1);
    // lv_obj_set_align(ui_Switch7, LV_ALIGN_CENTER);
    // lv_obj_set_style_bg_color(ui_Switch7, lv_color_hex(0x0B6218), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Switch7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_bg_color(ui_Switch7, lv_color_hex(0x24BE42), LV_PART_KNOB | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Switch7, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Image8, game2_cd, LV_EVENT_ALL, NULL);

    ui_Image9 = lv_btn_create(ui_TabPage3);
    lv_obj_set_width(ui_Image9, 284);
    lv_obj_set_height(ui_Image9, 48);
    lv_obj_set_x(ui_Image9, -5);
    lv_obj_set_y(ui_Image9, 65);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Image9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Image9, &ui_img_1662400658, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Image9);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label9, -77);
    lv_obj_set_y(ui_Label9, -1);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Snake for eating");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x0F7E2F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_Switch8 = lv_switch_create(ui_Image9);
    // lv_obj_set_width(ui_Switch8, 60);
    // lv_obj_set_height(ui_Switch8, 35);
    // lv_obj_set_x(ui_Switch8, 101);
    // lv_obj_set_y(ui_Switch8, -1);
    // lv_obj_set_align(ui_Switch8, LV_ALIGN_CENTER);
    // lv_obj_set_style_bg_color(ui_Switch8, lv_color_hex(0x0B6218), LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Switch8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_set_style_bg_color(ui_Switch8, lv_color_hex(0x24BE42), LV_PART_KNOB | LV_STATE_DEFAULT);
    // lv_obj_set_style_bg_opa(ui_Switch8, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_Image9, game3_cd, LV_EVENT_ALL, NULL);
}
